### ISSUE TITLE
(file-missing "Cannot open load file" "No such file or directory" "lsp-common")

### ISSUE THREAD

**Issue by damon-kwok** [emacs-lsp/lsp-clangd#19]
(file-missing "Cannot open load file" "No such file or directory" "lsp-common")

**Comment by tee3** [comment]
Have you updated `lsp-mode` lately?

`lsp-mode` has recently been completely rewritten and `clangd` is now supported internally.  As a result, `lsp-clangd` is only useful when using the previous `lsp-mode` implementation.

Please see the discussion here https://github.com/emacs-lsp/lsp-clangd/issues/11#issuecomment-445587207 for how you should be using it now.

**Comment by damon-kwok** [comment]
lsp-clangd.el line 27:(require 'lsp-common)

**Comment by tee3** [comment]
You need to follow the instructions in the link I provided above.  `lsp-mode` has been completely rewritten.  Can you try to follow that and let me know if that works for you?

**Comment by damon-kwok** [comment]
i see, thanks
