### ISSUE TITLE
std libraries not recognised

### ISSUE THREAD

**Issue by gregnwosu** [emacs-lsp/lsp-clangd#2]
when i run lsp-clangd it doesnt recognise standard libaries such as std
*Messages* buffer:
```Error from the Language Server: method not found (Method not Found)```

*lsp-clangd-c++ stderr*
```Error -32601: method not found
--> {"error":{"code":-32601,"message":"method not found"},"id":74,"jsonrpc":"2.0"}
<-- {"id":75,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":0,"line":8},"textDocument":{"uri":"file:///Users/greg/dev/c/src/main.cpp"}}}

--> {"id":75,"jsonrpc":"2.0","result":[]}
```

os: macos sierra
llvm: 6.0.0 installed via homebrew
config:
```
(use-package lsp-clangd
  :quelpa (lsp-clangd :fetcher github :repo "tee3/lsp-clangd")
  :hook (
  (c-mode . lsp-clangd-c-enable)
  (c++-mode . lsp-clangd-c++-enable)
  (objc-mode . lsp-clangd-objc-enable)))

(use-package lsp-mode
          :ensure t
          :config
          ;; make sure we have lsp-imenu everywhere we have LSP
          (require 'lsp-imenu)
          (projectile-mode)
          :hook ((solidity-mode . lsp-solidity-enable)
                 (lsp-mode . turn-on-smartparens-mode)
                 (lsp-mode . flycheck-mode)
                 (lsp-after-open . lsp-enable-imenu)))

```
code:

```
#include <iostream>

int main() {
   std::cout << "Hello world";
   int x = 3 / 3;
   std::cout << "ddd";
   return 0;
}
```

**Comment by tee3** [comment]
I don't believe the configuration of `lsp-mode`, which is what `lsp-clangd` does, can do much to fix this issue.  If the `lsp-mode` and the desired version of `clangd` is running and the `compile_commands.json` is correct, the configuration is correctly specified.

There have been many improvements to `clangd` over the past few months, so you might install the `HEAD` of the `llvm` formula from Homebrew (`brew install llvm --HEAD`) and set the `clangd` executable to the one created (which is not on the path) at `/usr/local/opt/llvm/bin/clangd`.  You will likely get better results using the newer version.  I do not know if this will fix the issue you are seeing, though.

I will try to do some experiments myself if I can find a few minutes.

**Comment by gregnwosu** [comment]
installing llvm --HEAD fixes the issue

**Comment by tee3** [comment]
@gregnwosu.  I'm working on updating the documentation to share this configuration.  Thanks for reporting back!
