### ISSUE TITLE
lsp deprecated lsp-define-stdio-client.

### ISSUE THREAD

**Issue by Ergus** [emacs-lsp/lsp-clangd#20]
As refered in: https://github.com/emacs-lsp/lsp-mode/issues/505 the syntax changed

**Comment by yyoncho** [comment]
This package is no longer needed, it is contained in lsp-mode.

**Comment by tee3** [comment]
@yyoncho Should we archive this repository and add some additional documentation to the README to minimize these sorts of issues?  Maybe a `CONTRIBUTING.md` file that says that?  I will do that if you think it is a good idea at this point.

**Comment by yyoncho** [comment]
@tee3 Achieving the repo will be ideal + bigger notice in the readme. @tarsius is going to remove it from melpa too.

**Comment by tee3** [comment]
I will do that today and refer to the portion of the `lsp-mode` README that describes how to configure it now.
